version: '3.8'

services:
  ntfy:
    image: binwiederhier/ntfy:latest
    container_name: ntfy-server
    restart: unless-stopped
    
    environment:
      - TZ=UTC
      - NTFY_BASE_URL=https://your-domain.com  # Update this with your domain
      - NTFY_CACHE_FILE=/var/cache/ntfy/cache.db
      - NTFY_ATTACHMENT_CACHE_DIR=/var/cache/ntfy/attachments
      - NTFY_BEHIND_PROXY=true
      - NTFY_AUTH_FILE=/var/lib/ntfy/auth.db
      - NTFY_AUTH_DEFAULT_ACCESS=deny-all
      - NTFY_ENABLE_LOGIN=true
      - NTFY_ENABLE_SIGNUP=false
    
    # Only expose to localhost - proxy will handle external traffic
    ports:
      - "127.0.0.1:8080:80"
    
    volumes:
      - ./ntfy-config:/etc/ntfy:ro
      - ./ntfy-cache:/var/cache/ntfy
      - ./ntfy-data:/var/lib/ntfy
    
    healthcheck:
      test: ["CMD-SHELL", "wget -q --tries=1 http://localhost:80/v1/health -O - | grep -Eo '\"healthy\"\\s*:\\s*true' || exit 1"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 40s
    
    command: serve

  # Nginx reverse proxy for SSL termination
  nginx:
    image: nginx:alpine
    container_name: ntfy-nginx
    restart: unless-stopped
    
    ports:
      - "80:80"
      - "443:443"
    
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro  # SSL certificates
    
    depends_on:
      - ntfy
    
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:80/health"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  default:
    name: ntfy-network
